name: Deploy Lambda with Terraform

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.tf'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment (for zipping Lambda)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install zip utility
      - name: Install zip utility
        run: sudo apt-get install -y zip

      # Step 4: Zip updated Lambda function
      - name: Zip Lambda function
        run: |
          cd lambda_function
          zip -r function.zip .

      # Step 5: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Step 6: Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      # Step 7: Apply Terraform (with auto-approve)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
