jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Set up Python environment (for zipping Lambda)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 4: Install zip utility
      - name: Install zip utility
        run: sudo apt-get install -y zip

      # Step 5: Zip updated Lambda function
      - name: Zip Lambda function
        run: |
          cd lambda_function
          zip -r function.zip .

      # Step 6: Verify ZIP file exists
      - name: Verify function.zip exists
        run: |
          if [ ! -f lambda_function/function.zip ]; then
            echo "Error: function.zip not found!"
            exit 1
          fi

      # Step 7: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Step 8: Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform
        env:
          TF_LOG: DEBUG

      # Step 9: Apply Terraform (with auto-approve)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
        env:
          TF_LOG: DEBUG

