name: Update Lambda Function

on:
  push:
    branches:
      - Main
    paths:
      - '**.py'

jobs:
  update-lambda:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install zip utility
      - name: Install zip utility
        run: sudo apt-get install -y zip

      # Step 3: Create ZIP file
      - name: Create function.zip
        run: |
          cd lambda_function
          zip -r function.zip .

      # Step 4: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 5: Create Lambda Function if not exists
      - name: Create Lambda Function if not exists
        run: |
          aws lambda get-function --function-name "SumFunction-dev" || \
          aws lambda create-function \
            --function-name "SumFunction-dev" \
            --runtime "python3.9" \
            --role "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/lambda_exec_role" \
            --handler "app.lambda_handler" \
            --zip-file fileb://lambda_function/function.zip

      # Step 6: Update Lambda Function
      - name: Update Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name "SumFunction-dev" \
            --zip-file fileb://lambda_function/function.zip
